# Generated by Django 4.2.7 on 2023-11-22 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='pizza',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('ingridients', models.CharField(max_length=400)),
                ('price', models.FloatField(default=0)),
                ('vegetarian', models.BooleanField(default=False)),
            ],
        ),
    ]
